name: Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: docker build -t my-spring-app .
      
      - name: Run Docker container
        run: docker run -p 8080:8080 -e SERVER_PORT=9090 my-spring-app
