name: Octo Organization CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
      - name: Close Stale Issues
        uses: actions/stale@v8
