name: Notify and close stale PRs after 10 days

on:
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read
  pull-requests: write
  repository-projects: read

jobs:
  check-stale-pr:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Jane Hello World Action
        uses: u0324020/actions-helloword@v1.0

      - name: Close Stale Issues
        uses: actions/stale@v4.1.1
    
    
