repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages: [commit-msg, prepare-commit-msg]
        additional_dependencies:
          ["@dgc-org/cz-conventional-changelog-for-jira", "conventional-changelog", "commitlint-config-jira", "commitlint-plugin-jira-rules"]
#  - repo: https://github.com/commitizen-tools/commitizen
#    rev: v2.37.0 # automatically updated by Commitizen
#    hooks:
#      - id: commitizen
#      - id: commitizen-branch
#        stages:
#          - post-commit
#          - push
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint
        args: ["-r", "~MD004,~MD013,~MD033"]
        exclude: "TFDOC.md|CHANGELOG.md"
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
    - id: dockerfile_lint
      # optional custom config
      args: [--dockerfile]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-json
      # check json rc files
      - id: check-json
        types: [file]
        files: |
          (?x)^(
            .releaserc
          )
      - id: check-yaml
        args: [--allow-multiple-documents]

#  - repo: https://github.com/python-jsonschema/check-jsonschema
#    rev: 0.19.2
#    hooks:
#      - id: check-github-workflows

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        exclude: "TFDOC.md"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --hook-config=terraform
          - --hook-config=--html=false
          - --hook-config=--path-to-file=../README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
#      - id: terraform_tfsec
      - id: checkov
        args:
          - --skip-check=CKV_AWS_274,CKV2_GHA_1
